from selenium.common import NoSuchElementException
from selenium.webdriver import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select

from BasePage import BasePage
from FinvizStockPage import FinvizStockPage, FinvizETFPage
import requests

import argparse
import sys
from argparse import ArgumentParser
from typing import Sequence, Optional
from pathlib import Path

def get_url():
    return "https://www.finviz.com"
def parse_csv_with_headers(csv_file_path):
    """
    This method was generated by Claude

    Parse a CSV file using the first line as keys and create dictionaries
    for the next 5 lines of data.

    Args:
        csv_file_path (str): Path to the CSV file

    Returns:
        list: List of dictionaries, where each dictionary uses header values as keys
    """
    with open(csv_file_path, 'r') as fp:
        lines = sum(1 for line in fp)
    try:
        with open(csv_file_path, 'r') as file:
            # Read and process header line
            headers = [h.strip().strip('"') for h in next(file).strip().split(',')]
            # Process exactly 5 data lines
            return [
                dict(zip(headers, [v.strip().strip('"') for v in line.strip().split(',')]))
                for line in (next(file) for _ in range(lines - 1))
            ]

    except FileNotFoundError:
        print(f"Error: File '{csv_file_path}' not found.")
    except StopIteration:
        print("Error: File does not contain enough lines.")
    except Exception as e:
        print(f"Error occurred: {str(e)}")

    return []
def user_input():
    valid_screeners = ["overview","financial","ownership","performance","technical","valuation","etf_performance"]
    while True:
        try:
            # 1. Take input and convert to integer
            user_input = input("Enter Screener name and Ticker Symbol seperated by a space or script-input: ")

            if user_input != "script-input":
               a_screener = user_input.split(" ")[0]
               position = valid_screeners.index(a_screener)

            if user_input.lower() == 'exit':
                print("Goodbye!")
                break
            return user_input

        except ValueError:
            # 3.
            valid_input = "overview financial ownership performance technical valuation etf_performance script-input"
            print()
            print("Error: Please enter one of these values.\n")
            print(valid_input)
            print()
def print_parameter_for_ticker(ticker, parameter, file_path):
    value = ''
    dict_list = parse_csv_with_headers(str(file_path))
    for a_dictionary in dict_list:

        if a_dictionary.get('Ticker') == ticker:
            keys = a_dictionary.keys()
            options = {print(y + " *", end=" ") for y in keys}
            print("All",end=" ")
            print()
            parameter = input("Enter a parameter from the options above: ")
            if parameter != 'All':
                value = a_dictionary.get(parameter)
                print()
                print(f"{parameter} - " + value)
            else:
                key_pairs = a_dictionary.items()
                var = {print(x) for x in key_pairs}
        else:
            continue
    return keys
def main(argv: Optional[Sequence[str]] = None):
    # 1. Create the ArgumentParser object with a description
    parser = argparse.ArgumentParser(
        description="A script shows stock screener parameters for a stock Ticker.",
        prog="my_script"  # Optional: specify a custom program name for help messages
    )

    # 2. Add arguments (positional and optional)
    # Positional argument: 'name' is required and has no leading dashes
    parser.add_argument("screener_name", help="The name of the screener.")
    parser.add_argument("ticker_group", help="The Ticker symbol.")

    # Optional argument: '-v' or '--verbose' acts as a flag
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",  # Stores True if the flag is present, False otherwise
        help="Increase output verbosity."
    )

    # 3. Parse the arguments
    input_args = parser.parse_args(argv)  # Pass argv to make the main function testable
    # If argv is None, parser.parse_args() automatically looks at sys.argv

    if input_args.verbose:
        print(f"Screener deployed. {input_args.screener_name}.")
        print(f"Ticker chosen. {input_args.ticker_group}.")

    print(parser.description)

    screener = None
    equity = None

    input_params = user_input()
    if input_params == "script-input":
        screener = input_args.screener_name
        equity = input_args.ticker_group
    else:
        screener = input_params.split(" ")[0]
        equity = input_params.split(" ")[1]

    finviz_home_page = FinvizHomePage('config.ini')
    finviz_home_page.open()
    finviz_home_page.maximize_window()
    finviz_home_page.close_tab(1)
    finviz_home_page.click_login()

    screener_page = finviz_home_page.click_screener()
    finviz_home_page.enter_ticker_values(equity)
    metric_label = None

    match screener:
        case "valuation":
            print("Looking at Valuation: ")
            metric_label = screener_page.click_valuation()

        case "technical":
            print("Looking at Technical: ")
            metric_label = screener_page.click_technical()

        case "performance":
            print("Looking at Performance: ")
            metric_label = screener_page.click_performance()

        case "etf_performance":
            print("Looking at ETF_Performance: ")
            metric_label = screener_page.click_etfperformance()

        case "overview":
            print("Looking at Overview: ")
            metric_label = screener_page.click_overview()

        case "financial":
            print("Looking at Financial: ")
            metric_label = screener_page.click_financial()

        case "ownership":
            print("Looking at Ownership: ")
            metric_label = screener_page.click_ownership()

        case _:
            print("Default Case")

    if metric_label != None:
        config_file_path = finviz_home_page.send_api_request(metric_label)
        keys = print_parameter_for_ticker(equity, 'Sector', config_file_path )
class FinvizHomePage(BasePage):
    driver = None

    def __init__(self, config_file='config.ini'):
        super().__init__(config_file)
        self.login = None
        self.driver = self.create_firefox_driver()

        # locators
        self.home = (By.XPATH, '//a[@href="/" and text()="Home"]')
        self.login = (By.XPATH, '//a[@href="/login"]')
        self.search = (By.ID, '_r_1_')
        self.screener = (By.XPATH, '//a[@href="/screener.ashx"]')
        self.decriptive = (By.XPATH, "//div[text()='Descriptive']")
        self.fundamental = (By.XPATH, "//div[text()='Fundamental']")
        self.technical = (By.XPATH, "//div[text()='Technical']")
        self.etf = (By.XPATH, "//div[text()='ETF']")
        self.ticker = (By.XPATH, "//input[@id='tickersInput']")
        self.ticker_button = (By.XPATH, "//button[@class='screener-combo-button fv-button screener_button is-arrow']")

        # This locator only shows up when searching for an ETF equity symbol
        self.etf_label = (By.XPATH, '//a[@title="Exchange Traded Fund"]')

        # temporary xpath to test select dropdown
        self.dividend_yield = (By.XPATH, '//select[@id="fs_fa_div"]')

        self.all_locators = [self.home, self.login, self.search, self.screener]

    def get_driver(self):
        return self.driver

    def open(self):
        self.driver.get(get_url())

    def quit(self):
        self.driver.quit()

    def close(self):
        self.driver.close()

    def close_tab(self, tab_number):
        window_handles = self.driver.window_handles

        # point driver at extra tab window_handle (Adobe Adblock Installed Tab) and close it.
        self.driver.switch_to.window(window_handles[tab_number])
        print("Tab with Label: " + str("'" + self.driver.title + "'") + " Has Been Closed")
        self.close()

        # get the updated windows_handles array and point driver at the remaining tab handle - there should  only
        # be one in the window_handles array. This is the Finviz webpage.
        window_handles = self.driver.window_handles
        self.driver.switch_to.window(window_handles[0])

        for a_locator in self.all_locators:
            self.element_exists(a_locator)

    def maximize_window(self):
        self.driver.maximize_window()

    def enter_search_value(self, value):
        self.driver.find_element(*self.search).send_keys(value + Keys.ENTER)
        firefox_driver = self.driver
        if self.is_etf():
            return FinvizETFPage(firefox_driver, value)
        else:
            return FinvizStockPage(firefox_driver, value)

    def enter_ticker_values(self,comma_delimited_values):
        self.driver.find_element(*self.ticker).send_keys(comma_delimited_values)
        self.driver.find_element(*self.ticker_button).click()

    def click_screener(self):
        self.driver.find_element(*self.screener).click()
        return ScreenerPage(self.driver)
    def click_descriptive(self):
        self.driver.find_element(*self.decriptive).click()
        return DescriptiveScreener(self.driver)
    def click_fundamental(self):
        self.driver.find_element(*self.fundamental).click()
        return FundamentalScreener(self.driver)
    def click_etf(self):
        self.driver.find_element(*self.etf).click()
        return ETFScreener(self.driver)
    def click_technical(self):
        self.driver.find_element(*self.technical).click()
        return TechnicalScreener(self.driver)

    def click_home(self):
        self.driver.find_element(*self.home).click()

    def click_login(self):
        from HomePage.LoginPage import LoginPage

        if not self.is_in_account():
            self.driver.find_element(*self.login).click()
            return LoginPage(self.driver)

    def is_etf(self):
        self.driver.implicitly_wait(1)
        if len(self.driver.find_elements(*self.etf_label)) > 0:
            return True
        return False

    def is_in_account(self):
        in_account = self.config.getboolean('browsers', 'logged_in')
        if in_account:
            return True
        return False

    def element_exists(self, web_element):
        try:
            self.driver.find_element(*web_element)
        except NoSuchElementException as e:
            print(e)

    def create_api_url(self):
        url = self.driver.current_url
        filter = url.split('?')[1]
        return self.api_url + filter + '&auth=' + self.api_key

    def send_api_request(self,metrics):
        # Metrics can be Overview, Value, Financial, etc...

        export_filename = str(self.csv_file).replace("export.csv",metrics+"_"+"export.csv")
        built_url = self.create_api_url()
        response = requests.get(built_url)
        open(export_filename, "wb").write(response.content)
        return export_filename
class ScreenerPage:

    def __init__(self, driver):
        self.driver = driver
        self.overview = (By.XPATH, "//a[text()='Overview']")
        self.valuation = (By.XPATH, "//a[text()='Valuation']")
        self.financial = (By.XPATH, "//a[text()='Financial']")
        self.ownership = (By.XPATH, "//a[text()='Ownership']")
        self.performance = (By.XPATH, "//a[text()='Performance']")
        self.technical = (By.XPATH, "//a[text()='Technical']")
        self.etfperf = (By.XPATH, "//a[text()='ETF Perf']")

    def click_overview(self):
        self.driver.find_element(*self.overview).click()
        return "overview"

    def click_valuation(self):
        self.driver.find_element(*self.valuation).click()
        return "valuation"

    def click_financial(self):
        self.driver.find_element(*self.financial).click()
        return "financial"

    def click_ownership(self):
        self.driver.find_element(*self.ownership).click()
        return "ownership"

    def click_performance(self):
        self.driver.find_element(*self.performance).click()
        return "performance"

    def click_technical(self):
        self.driver.find_element(*self.technical).click()
        return "technical"

    def click_etfperformance(self):
        self.driver.find_element(*self.etfperf).click()
        return "etf_performance"
class DescriptiveScreener:

    def __init__(self, driver):
        self.driver = driver

        self.exchange = (By.XPATH, '//select[@id="fs_exch"]')

    def select_exchange(self, value):
        select = Select(self.driver.find_element(*self.exchange))
        select.select_by_visible_text(value)
class FundamentalScreener:

    def __init__(self, driver):
        self.driver = driver

        #locators for Fundamental Screener
        self.price_to_earning = (By.XPATH, '//select[@id="fs_fa_pe"]')

    def select_ptoe(self,value):
        select = Select(self.driver.find_element(*self.price_to_earning))
        select.select_by_visible_text(value)
class TechnicalScreener:

    def __init__(self, driver):
        self.driver = driver

        #locators
        self.performance = (By.XPATH, '//select[@id="fs_ta_perf"]')

    def select_performance(self,value):
        select = Select(self.driver.find_element(*self.performance))
        select.select_by_visible_text(value)
class ETFScreener:

    def __init__(self, driver):
        self.driver = driver

        #locators
        self.single_category = (By.XPATH, '//select[@id="fs_etf_category"]')

    def select_single_category(self,value):
        select = Select(self.driver.find_element(*self.single_category))
        select.select_by_visible_text(value)

if __name__ == "__main__":
    main()



